version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_post_service_nextgenlearn
    environment:
      POSTGRES_DB: ngl
      POSTGRES_USER: userngl
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432" 
    networks:
      - backend-network

  post-service:
    build: ./Post-service
    container_name: post_service_nextgenlearn
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Post-service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend-network

  user_db:
    image: postgres:latest
    container_name: postgres_user_service_nextgenlearn
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user_db
      POSTGRES_PASSWORD: 'mypassword'
    ports:
      - "5435:5432"
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./User-service
    container_name: user_service_nextgenlearn
    command: python manage.py runserver 0.0.0.0:8001
    volumes:  
      - ./User-service:/app
    ports:
      - "8001:8001"
    depends_on:
      - user_db
    networks:
      - backend-network

  
  review-service:
    build: ./Review-service
    container_name: review_service_nextgenlearn
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./Review-service:/app
    ports:
      - "8003:8003"
    networks:
      - backend-network
  
  interaction-service:
    build: ./Interaction-service
    container_name: interaction-service_nextgenlearn
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - ./Interaction-service:/app
    ports:
      - "8004:8004"
    networks:
      - backend-network

  video_db:
    image: postgres:latest
    container_name: postgres_video_service_nextgenlearn
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: user_video_db
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5434:5432"
    networks:
      - backend-network

  video-service:
    build: ./Video-service
    container_name: video-service_nextgenlearn
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - ./Video-service:/app
    ports:
      - "8005:8005"
    depends_on:
      - video_db
    networks:
      - backend-network

  about-service:
    build:
      context: ./About-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./About-service:/app
    networks:
      - backend-network

  frontend:
    build: ./Frontend
    container_name: frontend_nextgenlearn
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
